remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Patrick Shyu
description: Patrick Shyu is a software engineer, entrepreneur, and social media creator. He creates content on tech, finance, and lifestyle and is an ex-Google / ex-Facebook software engineer.
logo: assets/ps.jpg
